# CloudFront Configuration
cloudfront_url: "di2fr1kjn7b4m.cloudfront.net"
# 考虑有些源站需要用自定义host，这时可以指定 备用域名host
host: "di2fr1kjn7b4m.cloudfront.net"
# 考虑有些配置是 http 直接 302 到 https
protocol: "https" # Protocol to use: "http" or "https"

files: |
  /input3.js
  # 多文件预热每个文件一行，以#开头的行会被忽略
  # 脚本同时支持上述格式和传统的YAML列表格式（使用'-'前缀）

# cloudfront 根据支持压缩格式的组合来区分缓存键
encodings:
  - "gzip, br" # 浏览器常用设置，如常用的“gzip, deflate, br, zstd” 就是这个，cloudfront会把不支持的格式排除，先后顺序无关
  #- "gzip" # 兼容只支持gzip的旧浏览器，需要单独进行请求
  #- "br" # 同理，只支持 Brotli 的请求
  - "" # 没有指定Accept-Encoding字段，如客户端程序直接请求

# 需要预热的 POP 点，可根据用户分布选择
# 这里可以查到比较全的pop点信息，https://www.feitsui.com/en/article/3
# 默认建议以下少数几个即可，对主要的区域性边缘缓存（Regional Edge Cache）做预热：https://aws.amazon.com/cloudfront/features/
pops:
  - "IAD89-C1" # North America (N.Virginia)
  # - "CMH68-P1" # North America (Ohio)
  # North America (Oregon)
  - "SFO53-C1" # North America (California)
  - "GRU1-C2" # South America (São Paulo)
  # - "DUB56-P1" # Ireland (Dublin)
  # - "LHR61-C2" # UK (London)
  - "FRA50-C1" # Germany (Frankfurt)
  - "BOM52-C1" # India (Mumbai)
  - "SIN2-P6" # Asia (Singapore)
  # - "ICN55-C1" # South Korea (Seoul)
  - "NRT20-P2" # Japan (Tokyo)
  - "SYD1-C1" # Australia (Sydney)
  # others
  # - "HKG62-C1" # China/Hong Kong (Hong Kong)
  - "DXB52-P1" # Middle East (Dubai)
