---
# Echo Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: demo
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
# Service https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/
apiVersion: v1
kind: Service
metadata:
  annotations:
    # 公网lb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    #  后端目标类型：instance 和 ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    #  enable cross zone load balancing
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    #  enable client availability zone affinity
    service.beta.kubernetes.io/aws-load-balancer-attributes: dns_record.client_routing_policy=availability_zone_affinity
    #  enable source IP affinity
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip
    # ssl证书设置
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxx
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #  如果后端是ssl端口，设置 ssl
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp

    # 健康检查 可以指定 tcp/http/https
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    #  可以直接指定流量端口：traffic-port 或指定端口 80
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: 200-399

  name: echo-server-service
  namespace: demo
  labels:
    app: echo-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: echo-server
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
